// app2/src/components/GeometryList.tsx
import type { JSX } from 'react'

interface GeometryListProps {
  store: any
  stroke?: number
  strokeMid?: number
  strokeBig?: number
  strokeLine?: number
}

interface GeometryItem {
  name: string
  element: any
  selected: boolean
  type: string
  context?: any
}

export function GeometryList({ store, stroke = 0.5, strokeBig = 2 }: GeometryListProps): JSX.Element {
  
  const handleClick = (name: string) => {
    const item = store.items[name] as GeometryItem | undefined;
    if (!item) return;
    
    // Toggle selection state
    store.update(name, { selected: !item.selected });
    
    // Apply visual feedback to the SVG element
    applyVisualFeedback(item.element, { ...item, selected: !item.selected }, stroke, strokeBig);
  };

  const getItemColor = (name: string) => {
    const item = store.items[name] as GeometryItem | undefined;
    if (item?.selected) {
      return item.context ? 'text-red-400' : 'text-yellow-400';
    }
    return 'text-white';
  };

  return (
    <div className="geometry-list">
      <h3>Geometry Items</h3>
      <p>Store has {Object.keys(store.items || {}).length} items</p>
      <ul>
        {store.items && Object.entries(store.items).map(([key, item]) => (
          <li 
            key={key}
            onClick={() => handleClick(key)}
            className={`cursor-pointer hover:underline ${getItemColor(key)}`}
          >
            {(item as GeometryItem).name} | {(item as GeometryItem).type}
          </li>
        ))}
      </ul>
    </div>
  )
}

// Apply visual feedback to SVG elements based on selection state
function applyVisualFeedback(element: any, shape: GeometryItem, stroke: number, strokeBig: number) {
  if (!element) return;
  
  try {
    if (shape.type === "point") {
      if (shape.selected) {
        element.setAttribute('fill', 'black');
        element.setAttribute('r', stroke.toString());
        // Show tooltip and background when selected
        if (element.tooltip) {
          element.tooltip.setAttribute('opacity', '1');
        }
        if (element.tooltipBg) {
          element.tooltipBg.setAttribute('opacity', '1');
        }
      } else {
        element.setAttribute('fill', 'red');
        element.setAttribute('r', strokeBig.toString());
        // Hide tooltip and background when not selected
        if (element.tooltip) {
          element.tooltip.setAttribute('opacity', '0');
        }
        if (element.tooltipBg) {
          element.tooltipBg.setAttribute('opacity', '0');
        }
      }
    }
    else if (shape.type === "circle" || shape.type === "line") {
      if (shape.selected) {
        element.setAttribute('stroke-width', strokeBig.toString());
        element.setAttribute('stroke', 'red');  // Make selected items red for visibility
      } else {
        element.setAttribute('stroke-width', stroke.toString());
        element.setAttribute('stroke', '#f06');  // Original color
      }
    }
  } catch (error) {
    console.error('Error applying visual feedback:', error);
  }
}

// app/src/GeometryList.svelte
<script>
  import { derived, get, writable } from "svelte/store";

  export let store;
  export let stroke = 0.5;
  export let strokeMid = 0.5;
  export let strokeBig = 2;
  export let strokeLine = 1.4;

  $: names = derived(store, ($s) => Object.keys($s));

  const selectShape = (element, shape) => {
    if (shape.type === "point") {
      if (shape.selected) {
        element.tooltip.map((x) => x.style("opacity", 0));
        element.dot.style("fill", "black").attr("r", stroke);
      } else {
        element.tooltip.map((x) => x.style("opacity", 1));
        element.dot.style("fill", "red").attr("r", strokeBig);
      }
    }
    if (shape.type === "circle" || shape.type === "line") {
      if (shape.selected) {
        element.style("stroke-width", stroke);
      } else {
        element.style("stroke-width", strokeBig);
      }
    }
  };
  const handleClick = (name) => {
    const s = get(store);
    const v = s[name];
    const e = v.element;
    const hasContext = v.context != null;
    console.log(name, "hasContext", hasContext, v);
    selectShape(e, v);
    if (hasContext) {
      const geometry = v.context;
      geometry.inputs.forEach((input) => {
        const currShape = s[input.name];
        const currElement = currShape.element;
        selectShape(currElement, { ...currShape, selected: v.selected });
        console.log("input name", input.name);
        store.update(input.name, { ...currShape, selected: !v.selected });
      });
    }
    store.update(name, { ...v, selected: !v.selected });
  };

  const colorItem = (name) => {
    const shape = get(store)[name];
    const selected = shape.selected;
    if (selected == true) {
      const isOutput = shape.context != null;
      const isInput = shape.context == null;
      if (isOutput) return "red";
      if (isInput) return "yellow";
      console.error("shape is not input or output");
      return "grey";
    } else return "white";
  };
</script>

<ul>
  {#each $names as name}
    <li
      class="geometry-item"
      on:click={() => handleClick(name)}
      on:keydown={() => handleClick(name)}
      style="color: {colorItem(name)}"
    >
      {name} | {get(store)[name].type}
    </li>
  {/each}
</ul>

<style>
  .geometry-item {
    cursor: pointer;
  }
  .geometry-item:hover {
    text-decoration: underline;
  }
</style>
